export const NEW_GAME = "NEW_GAME";
export const ADD_GAME_TO_GAME_LIST = "ADD_GAME_TO_GAME_LIST";
export const BUILD_ACTIVE_GAME_LIST = "BUILD_ACTIVE_GAME_LIST";
export const UPDATE_GAME_IN_GAME_LIST = "UPDATE_GAME_IN_GAME_LIST";